# @see https://docs.travis-ci.com/user/docker/
language: php

services:
  - docker

script:
  - sudo service mysql stop # travis has a mysql server up, must stop it for mariadb port
  - make ENV=unittest stop clean init-db start unittest
